import type { NextPage } from 'next'
import Head from 'next/head'
import { BaseStyles } from '@primer/react';
import { Navbar } from '../components/Navbar';
import HeroSection from '../components/landing/HeroSection';
import Footer from '../components/landing/Footer';
import toast, { Toaster } from 'react-hot-toast';
import { useEffect } from 'react';
import { useSession } from 'next-auth/react';
import Loader from '../components/Loader';

const Home: NextPage = () => {
  const session = useSession();
  useEffect(() => {
    if (session.status == 'authenticated')
      toast(`Hi, ${session.data.user?.name} you are back, again.`, {
        icon: '👏'
      });
    return () => {};
  });

  return session.status == 'loading' ? (
    <Loader />
  ) : (
    <BaseStyles>
      <Toaster />
      <Head>
        <title>HasuraChamp</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <nav className="fixed bg-none	z-40 top-0 left-0 right-0 backdrop-blur bg-clip-padding backdrop-filter bg-opacity-10">
        <Navbar />
      </nav>

      <main>
        <HeroSection />
        <Footer />
      </main>
    </BaseStyles>
  );
};

export default Home
